site_name: 'Open Sustainable Technology'
site_url: 'https://opensustain.tech/'
site_description: 'Open technology projects sustaining stable climate, energy supply and vital natural resources'
repo_name: 'protontypes/open-sustainable-technology'
repo_url: 'https://github.com/protontypes/open-sustainable-technology'
base_url: 'https://opensustain.tech/'
edit_uri: ''
nav:
  - Projects: index.md
  - Reports:
      2023: https://report.opensustain.tech 
  - Education: education.md
  - Contribute: contributing.md
  - Blog:
      2022:
        - "You can preserve the Earth's livability with open source" : blog/you_can_preserve_the_earth_s_livability_with_open_source.md  
        - "Impact and potential of open source on climate technology": blog/impact_and_potential_of_open_source_on_climate_technology.md
        - "Openness as a key indicator for sustainable investment": blog/openness_as_a_key_indicator_for_sustainable_investment.md
      2021:
        - "Open Principles for a Sustainable Technology Transition": blog/open_principles_for_a_sustainable_technology_transition.md
      2020:
        - "Gathering Open Sustainable Technology": blog/gathering_open_sustainable_technology.md

theme:
  name: 'material'
  custom_dir: 'docs/overrides'
  logo: 'logo.png'
  favicon: 'favicon.png'
  palette:
        primary: 'teal'
        accent: 'light'
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.indexes
    - toc.integrate
    - search.highlight
    - search.suggest
    
extra_css:
    - css/extra.css

markdown_extensions:
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra:
  generator: false
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/protontypes
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/company/protontypes
