#
# YAML file configuring the actions to take when releasing to production
#
# > Syntax tips here: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
#
name: Updating the data

on: 
  workflow_dispatch:
    logLevel:
      description: 'Log level'
      required: true
      default: 'warning'
      type: choice
      options:
        - info
        - warning
        - debug
  #schedule:
  #  - cron: '25 5 * * WED'

jobs:
  build-and-run-updating:
    name: Maintain listing

    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write

    concurrency:
      group: ${{ github.workflow }}-updating
      cancel-in-progress: true   

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: "Create UV installation"
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.9.2"

      - name: Installing packages 
        run: |
          uv venv
          uv pip install -r .github/workflows/maintenance/requirements.txt

      - name: Restore cache
        id: cache-restore
        uses: actions/cache/restore@v4
        with:
          path: maintenance-diskcache/
          key: maintenance-cache

      - name: Running the script
        run: uv run .github/workflows/maintenance/maintenance_script.py
                
      - name: Save cache
        id: cache-save
        uses: actions/cache/save@v4
        with:
          path: maintenance-diskcache/
          key: ${{ steps.cache-restore.outputs.cache-primary-key }}

      - name: Defining Git identity 
        run: | 
          git config user.name github_actions
          git config user.email github_actions@opensustain.tech
      
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: "maintenance/${{ github.run_id }}"
          base: "main"
          title: "Updating links (${{ github.run_id }})"